// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeuroAira.Database;

#nullable disable

namespace NeuroAira.Migrations
{
    [DbContext(typeof(NeuroAiraDbContext))]
    [Migration("20240317102850_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.28");

            modelBuilder.Entity("NeuroAira.Models.MetaConversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserConversationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserConversationId")
                        .IsUnique();

                    b.ToTable("MetaConversations");
                });

            modelBuilder.Entity("NeuroAira.Models.UserConversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ConversationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Jailbreak")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Model")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserConversations");
                });

            modelBuilder.Entity("NeuroAira.Models.MetaConversation", b =>
                {
                    b.HasOne("NeuroAira.Models.UserConversation", "UserConversation")
                        .WithOne("MetaConversation")
                        .HasForeignKey("NeuroAira.Models.MetaConversation", "UserConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserConversation");
                });

            modelBuilder.Entity("NeuroAira.Models.UserConversation", b =>
                {
                    b.Navigation("MetaConversation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
